### ISSUE TITLE
The missing engine.py file

### ISSUE THREAD

**Issue by molumitu** [akifumi-wachi-4/spolf#1]
Hello, you really did a good job, and I am interested in learning more details from your source code. You mentioned that replacing `safety-gym/safety_gym/envs/engine.py` using `/safety_gym_discrete/engine.py`,  but I don't find the `engine.py` in the safety_gym_discrete folder. Maybe you forget to add and commit it to this repository? I would sincerely appreciate it if you can respond to my issue!

**Comment by yunyuewei** [comment]
Hello, we did modified  `engine.py` in the early experiment. Now we put modification outside the library.  You can directly run the code after configuring the [safety-gym](https://github.com/openai/safety-gym) and [MuJoCo](http://www.mujoco.org/) environment :)
